### ISSUE TITLE
Silent install failed with error code 5 possible vm.max.count issue?

### ISSUE THREAD

**Issue by ghost** [dimasukr/mstr-docker#1]
Thank you for publishing this and for sharing your code. 
I've been able to get most of the build to complete, but it fails during the MicroStrategy install.

   ++ cd /mnt/host_data/mstr_install/Installations/QueryReportingAnalysis_Linux
   ++ ./setup.sh -silent -options /mstr_demo/mstr_install_options.ini
   ...done.
   Checking file integrity.........done.
   Silent installation failed with error code: 5. See log file at:
   /tmp/mstrinst.12899/error.log

The error.log (attached) shows everything OK, except that the vm.max.count should be 5242880. Here is the clip from the log file:

   MicroStrategy requirements:
   WARNING: Setup has detected that the kernel setting vm.max_map_count in this system is low. The current value is 262144. The required value is 5242880.
   Increase it by adding the line:
      vm.max_map_count=5242880
   to the configuration file /etc/sysctl.conf and reboot the system.
   Keeping the current setting may cause server memory allocation failure before the memory resource is exhausted.

I attempted to change this in the host OS at the shell, but get an error that it's read only. I also tried adding it into the build_main.sh with no luck. Did you encounter this problem? Any suggestions?

[error.log.txt](https://github.com/dimasukr/mstr-docker/files/1065270/error.log.txt)

**Comment by dimasukr** [comment]
Here is what you should try:
Make sure the host OS (or VM if you run docker toolbox) has vm.max_map_count=5242880
You can then modify run command with -ipc=host

I will release new version of these files in next month where build will be in container itself where this issue also happened and provide more detailed instructions on how I fixed it

**Comment by fas3r** [comment]
Hello @dimasukr ,

When is plan the release  of the new version please ?

**Comment by mstruser** [comment]
Hello @sparker-org ,
Were you able to run this whole thing as a container successfully?
If yes, could you please tell me what all problems you faced and how did you resolve those?
Thanks,
Alok
