### ISSUE TITLE
Problem during execution of build_main.sh

### ISSUE THREAD

**Issue by fas3r** [dimasukr/mstr-docker#2]
Hello, 

At the end of the execution of the script I get the following error. Any idea how to correct it ? 

+ docker run --name mstr-install-demo -v /opt//MicroStrategy:/mnt/host_data/mstr_install --shm-size=1g --hostname=mstr-01 -it mstr-pre-demo /bin/bash -c '${DEMO_INSTALL_HOME}/mstr_install.sh'
/bin/bash: /mstr_demo/mstr_install.sh: Permission denied

Thank you.

**Comment by mojari** [comment]
What was the solution for this.
