### ISSUE TITLE
new version ? 

### ISSUE THREAD

**Issue by fas3r** [dimasukr/mstr-docker#4]
Hello, 

in one of your comment you were saying that you would publish a newer version earlier this year, do you have a status on that by any chance ? Or this not be published ?

thanks.

**Comment by dimasukr** [comment]
We are switching to Kubernetes which needs some additional work that takes more then expected
I don't know when exactly it will be complete

**Comment by fas3r** [comment]
Hello @dimasukr, any news ?

Thanks
