### ISSUE TITLE
question about com.genesys.gcxi.mstr.utils.jar

### ISSUE THREAD

**Issue by fas3r** [dimasukr/mstr-docker#5]
Hello @dimasukr ,

what are com.genesys.gcxi.mstr.utils.jar and com.genesys.gcxi.mstr.security.jar ? 

Can it be use outside of docker to rename / update the hostname, dsn, etc ?  ( on a classical setup when using the silent install mode ).

BR
fas3r

**Comment by fas3r** [comment]
hello @dimasukr ,

any chance to get an answer please ? 

Thanks

**Comment by dimasukr** [comment]
These are internal utilities of my employer.
We use MSTR api and so they just package stuff into command line from it
They are included as binary blibs here

You can use them but I can't really provide support for them
